# Cleanup script - remove old documentation files
$projectRoot = "E:\FRONT END\Secured-Data-App"
Set-Location $projectRoot

$filesToDelete = @(
    "AUDIT_DOCUMENTATION_INDEX.md",
    "AUDIT_FINAL_SUMMARY.md",
    "CODEBASE_AUDIT_REPORT.md",
    "CODERABBIT_IMPLEMENTATION_SUMMARY.md",
    "CODERABBIT_SUGGESTIONS.md",
    "COMPLETE_DELIVERABLES.md",
    "COMPLETE_IMPLEMENTATION.md",
    "COMPLETE_SETUP_GUIDE.md",
    "COMPLETE_SYSTEM_STATUS.md",
    "COMPLETION_CHECKLIST.md",
    "COMPLETION_REPORT.md",
    "DEPLOYMENT_GUIDE.md",
    "DOCUMENTATION_COMPLETE_INDEX.md",
    "DOCUMENTATION_INDEX.md",
    "DOCUMENTATION_INDEX_COMPLETE.md",
    "ENVIRONMENT_CONFIG.md",
    "EXECUTIVE_SUMMARY.md",
    "FILE_INVENTORY.md",
    "FINAL_DELIVERY_SUMMARY.md",
    "FINAL_PHASE_3_SUMMARY.md",
    "FULL_STACK_COMPLETION_REPORT.md",
    "GO_LIVE_CHECKLIST.md",
    "HOW_TO_START_SERVERS.md",
    "IMMEDIATE_NEXT_STEPS_EXECUTED.md",
    "IMPLEMENTATION_COMPLETE.md",
    "IMPLEMENTATION_GUIDE.md",
    "JWT_FIX_SUMMARY.md",
    "JWT_TOKEN_FIX.md",
    "LIVE_SERVER_STATUS.md",
    "LIVE_SYSTEM_STATUS.md",
    "MONGODB_TIMEOUT_FIX.md",
    "NEXT_STEPS.md",
    "PRODUCTION_READY.md",
    "PROGRESS_LOG_FINAL.md",
    "QUICK_FIX_GUIDE.md",
    "QUICK_REFERENCE.md",
    "QUICK_START.md",
    "QUICK_TEST.md",
    "README_FINAL.md",
    "REMAINING_TASKS_LOG.md",
    "SERVERS_RUNNING.md",
    "SERVERS_STARTED_FUNCTIONALITY_TEST.md",
    "SERVERS_STATUS_AND_TESTING.md",
    "SERVER_STARTUP_LOG.md",
    "SYSTEM_STATUS.md",
    "TASK_LOGS_INDEX.md",
    "TEST_NOW.md",
    "UAT_READINESS_REPORT.md",
    "UAT_TESTING_GUIDE.md",
    "SESSION_COMPLETE_PHASE_4.md",
    "SESSION_COMPLETE_SERVERS_STARTED.md",
    "SESSION_FIX_SUMMARY.md",
    "SESSION_PHASE_4_START.md",
    "SESSION_SUMMARY_JAN_25.md",
    "PHASE_2_COMPLETION_SUMMARY.md",
    "PHASE_3_1_COMPLETION.md",
    "PHASE_3_CHECKLIST.md",
    "PHASE_3_COMPLETION.md",
    "PHASE_3_IMPLEMENTATION_SUMMARY.md",
    "PHASE_3_QUICK_REFERENCE.md",
    "PHASE_3_STATUS.md",
    "PHASE_3_VERIFICATION_COMPLETE.md",
    "PHASE_4_1_COMPLETION.md",
    "PHASE_4_COMPLETION_SUMMARY.md",
    "PHASE_4_COMPREHENSIVE_SUMMARY.md",
    "PHASE_4_DOCUMENTATION_INDEX.md",
    "PHASE_4_IMPLEMENTATION_CHECKLIST.md",
    "PHASE_4_QUICK_REFERENCE.md",
    "PHASE_4_QUICK_START.md",
    "PHASE_4_ROADMAP.md",
    "PHASE_4_STATUS.md",
    "PHASE_4_VISUAL_ARCHITECTURE.md"
)

$deleted = 0
foreach ($file in $filesToDelete) {
    if (Test-Path $file) {
        Remove-Item $file -Force
        Write-Host "Deleted: $file"
        $deleted++
    }
}

Write-Host "`nCleanup complete! Deleted $deleted files."
